import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    {
      text: "第1章",
      icon: "creative",
      collapsable: true,
      prefix: "1/",
      link: "1/",
      children: "structure",
    },

    {
      text: "第2章",
      icon: "creative",
      collapsable: true,
      prefix: "2/",
      link: "2/",
      children: "structure",
    },
    {
      text: "第3章",
      icon: "creative",
      collapsable: true,
      prefix: "3/",
      link: "3/",
      children: "structure",
    },
    {
      text: "第4章",
      icon: "creative",
      collapsable: true,
      prefix: "4/",
      link: "4/",
      children: "structure",
    },
    {
      text: "第5章",
      icon: "creative",
      collapsable: true,
      prefix: "5/",
      link: "5/",
      children: "structure",
    },
    {
      text: "第6章",
      icon: "creative",
      collapsable: true,
      prefix: "6/",
      link: "6/",
      children: "structure",
    },
    {
      text: "第7章",
      icon: "creative",
      collapsable: true,
      prefix: "7/",
      link: "7/",
      children: "structure",
    },
    {
      text: "第8章",
      icon: "creative",
      collapsable: true,
      prefix: "8/",
      link: "8/",
      children: "structure",
    },
    {
      text: "第9章",
      icon: "creative",
      collapsable: true,
      prefix: "9/",
      link: "9/",
      children: "structure",
    },
    {
      text: "第10章",
      icon: "creative",
      collapsable: true,
      prefix: "10/",
      link: "10/",
      children: "structure",
    },
    {
      text: "第11章",
      icon: "creative",
      collapsable: true,
      prefix: "11/",
      link: "11/",
      children: "structure",
    },
    {
      text: "第12章",
      icon: "creative",
      collapsable: true,
      prefix: "12/",
      link: "12/",
      children: "structure",
    },

    {
      text: "第14章",
      icon: "creative",
      collapsable: true,
      prefix: "14/",
      link: "14/",
      children: "structure",
    },
    {
      text: "第15章",
      icon: "creative",
      collapsable: true,
      prefix: "15/",
      link: "15/",
      children: "structure",
    },
    {
      text: "第16章",
      icon: "creative",
      collapsable: true,
      prefix: "16/",
      link: "16/",
      children: "structure",
    },
    {
      text: "第17章",
      icon: "creative",
      collapsable: true,
      prefix: "17/",
      link: "17/",
      children: "structure",
    },
    {
      text: "第18章",
      icon: "creative",
      collapsable: true,
      prefix: "18/",
      link: "18/",
      children: "structure",
    },
  ],
});
